# 테스트로 작성한 코드고 실제로 실행해본 적 없음

name: Test Workflow

on: 
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: |
        # 테스트 실행 스크립트
        echo "Running tests..."
        # 테스트 성공 가정

    - name: Trigger webhook on success
      if: success()
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"ref": "${{ github.ref }}"}' [웹훅 URL]
